all:
	gcc -o user1 user1.c -I../library_files -L../library_files -lmsocket
	gcc -o user2 user2.c -I../library_files -L../library_files -lmsocket
	gcc -o user3 user3.c -I../library_files -L../library_files -lmsocket
	gcc -o user4 user4.c -I../library_files -L../library_files -lmsocket
clean:
	rm user1 user2 user3 user4